# Azure DevOps Pipeline YAML
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - powershell: |
      $apiUrl = "https://azurenamingtool-ggc4gxb7cxbpb8ef.centralus-01.azurewebsites.net/api/Admin/GetAdminLog"
      $apiKey = "$(API_KEY)"  # Store this as a secret variable in Azure DevOps
      $adminPassword = "$(ADMIN_PASSWORD)"  # Also stored as a secret variable

      # Define headers as shown in the curl example
      $headers = @{
          "APIKey" = $apiKey
          "AdminPassword" = $adminPassword
          "accept" = "*/*"
      }

      # Call the API
      Invoke-RestMethod -Uri $apiUrl -Method Get -Headers $headers
    displayName: "Get Admin Log"
